const constants = {
  USERS: 'Users',
  INVENTORIES: 'Inventories',
  ITEMS: 'Items',
  REPORT_AUTH_STATUS: 'REPORT_AUTH_STATUS',
  GET_USER_DETAILS: 'GET_USER_DETAILS',
  GET_OWN_INVENTORIES: 'GET_OWN_INVENTORIES',
  LOG_OUT: 'LOG_OUT',
  GET_SHARED_INVENTORIES: 'GET_SHARED_INVENTORIES',
  GET_INVENTORY_USERS: 'GET_INVENTORY_USERS',
  GET_INVENTORY_OWNER: 'GET_INVENTORY_OWNER',
  GET_INVENTORY_ITEMS:'GET_INVENTORY_ITEMS',
  SET_ACTIVE_INVENTORY: 'SET_ACTIVE_INVENTORY',
  SET_ACTIVE_ITEM: 'SET_ACTIVE_ITEM',
  SET_ACTIVE_ITEM_PRICE: 'SET_ACTIVE_ITEM_PRICE',
  GET_ACTIVE_INVENTORY_ITEMS: 'GET_ACTIVE_INVENTORY_ITEMS',
  CLEAR_ACTIVE_INVENTORY: 'CLEAR_ACTIVE_INVENTORY',
  JOIN_INVENTORY: 'JOIN_INVENTORY',
  SAVE_ITEM_TO_FIREBASE: 'SAVE_ITEM_TO_FIREBASE',
  ADD_ITEM_TO_INVENTORY: 'ADD_ITEM_TO_INVENTORY'
}
export default constants